/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TweetsRouteImport } from './routes/tweets'
import { Route as PautasRouteImport } from './routes/pautas'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as NoticiaRouteImport } from './routes/noticia'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as ArquivoRouteImport } from './routes/arquivo'
import { Route as IndexRouteImport } from './routes/index'

const TweetsRoute = TweetsRouteImport.update({
  id: '/tweets',
  path: '/tweets',
  getParentRoute: () => rootRouteImport,
} as any)
const PautasRoute = PautasRouteImport.update({
  id: '/pautas',
  path: '/pautas',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaRoute = NoticiaRouteImport.update({
  id: '/noticia',
  path: '/noticia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivoRoute = ArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/auditoria': typeof AuditoriaRoute
  '/dashboard': typeof DashboardRoute
  '/mapa': typeof MapaRoute
  '/noticia': typeof NoticiaRoute
  '/noticias': typeof NoticiasRoute
  '/pautas': typeof PautasRoute
  '/tweets': typeof TweetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/auditoria': typeof AuditoriaRoute
  '/dashboard': typeof DashboardRoute
  '/mapa': typeof MapaRoute
  '/noticia': typeof NoticiaRoute
  '/noticias': typeof NoticiasRoute
  '/pautas': typeof PautasRoute
  '/tweets': typeof TweetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/auditoria': typeof AuditoriaRoute
  '/dashboard': typeof DashboardRoute
  '/mapa': typeof MapaRoute
  '/noticia': typeof NoticiaRoute
  '/noticias': typeof NoticiasRoute
  '/pautas': typeof PautasRoute
  '/tweets': typeof TweetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arquivo'
    | '/auditoria'
    | '/dashboard'
    | '/mapa'
    | '/noticia'
    | '/noticias'
    | '/pautas'
    | '/tweets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arquivo'
    | '/auditoria'
    | '/dashboard'
    | '/mapa'
    | '/noticia'
    | '/noticias'
    | '/pautas'
    | '/tweets'
  id:
    | '__root__'
    | '/'
    | '/arquivo'
    | '/auditoria'
    | '/dashboard'
    | '/mapa'
    | '/noticia'
    | '/noticias'
    | '/pautas'
    | '/tweets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquivoRoute: typeof ArquivoRoute
  AuditoriaRoute: typeof AuditoriaRoute
  DashboardRoute: typeof DashboardRoute
  MapaRoute: typeof MapaRoute
  NoticiaRoute: typeof NoticiaRoute
  NoticiasRoute: typeof NoticiasRoute
  PautasRoute: typeof PautasRoute
  TweetsRoute: typeof TweetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tweets': {
      id: '/tweets'
      path: '/tweets'
      fullPath: '/tweets'
      preLoaderRoute: typeof TweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pautas': {
      id: '/pautas'
      path: '/pautas'
      fullPath: '/pautas'
      preLoaderRoute: typeof PautasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia': {
      id: '/noticia'
      path: '/noticia'
      fullPath: '/noticia'
      preLoaderRoute: typeof NoticiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivo': {
      id: '/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof ArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquivoRoute: ArquivoRoute,
  AuditoriaRoute: AuditoriaRoute,
  DashboardRoute: DashboardRoute,
  MapaRoute: MapaRoute,
  NoticiaRoute: NoticiaRoute,
  NoticiasRoute: NoticiasRoute,
  PautasRoute: PautasRoute,
  TweetsRoute: TweetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
